### PR TITLE
Feat stat tracker #least accurate team

### PR DESCRIPTION
**Pull request by skim1027**
Add test and methods for #least_accurate_team, #teams_shots_goals_ratio & #total_shots

### CODE REVIEW

**Review by scottdevoss — CHANGES_REQUESTED** [review]
For all the methods on "Season Statistics" they are supposed to take the "season id" as an argument and be able to return the team name from that given season. I think you can still work off of what you started - it just needs to be able to take an argument.

**Comment by skim1027** [comment]
thanks Scott for the call out - working on fixing it now and will let everyone know when I re-submit

**Comment by skim1027** [comment]
changes implemented

**Comment by skim1027** [comment]
Change has been implemented

**Review by delaneymiranda1 — APPROVED** [review]
Great catch from Scott. Great job updating these methods with the season argument.

**Review by scottdevoss — APPROVED** [review]
Thank you for making those changes. Great job incorporating the (season number) argument to you helper methods - that's a tricky one!

**Pull request merged**
