### PR TITLE
Feat statrack #count of games by season

### PR DESCRIPTION
**Pull request by skim1027**
Update to include #count_of_games_by_season (lines 113 - 119)
(changes from PR 1, 2 & 3 merged) 

Please review and let me know if my tests look sufficient.  I can also update to include the entire hash as we expect to see.

### CODE REVIEW

**Review by scottdevoss — CHANGES_REQUESTED** [review]
Method looks good! That's a good point about the test. I would probably suggest including the entire hash as shown in the spec harness since it's relatively small.(not sure if that effects simplecov coverage). Interested in what others think!

**Comment by mbkuhl** [comment]
I think Scott has a good point. If we're running through the full dataset anyways, we might as well compare it to the full Hash since it's not that large.

**Comment by skim1027** [comment]
This has been updated for both count_of_games_by_season and percentage_home_wins.

**Review by scottdevoss — APPROVED** [review]
Looks good to me! Thank you for making those changes to the test.

**Comment by delaneymiranda1** [comment]
Looks great!

**Pull request merged**
