### PR TITLE
Feat stat tracker #most accurate team

### PR DESCRIPTION
**Pull request by mbkuhl**
This pull request will implement StatTracker #most_accurate_team.

I think we're all creating helper methods that are accomplishing a lot of the same thing, but we can go through and find those/determine which one is the best and most efficient later.

### CODE REVIEW

**Review by scottdevoss — CHANGES_REQUESTED** [review]
Hey Mike, same as what I mentioned to Sooyung for all the methods on "Season Statistics" they are supposed to take the "season id" as an argument and be able to return the team name from that given season. I think you can still work off of what you started - it just needs to be able to take an argument. Does that make sense?
So I think it should be #most_accurate_team(season_id)

**Review by mbkuhl — COMMENTED** [review]
Here are the new changes for most_accurate_team based on season as opposed to over all seasons.

**Review by skim1027 — APPROVED** [review]
Great way to implement the season helper methods!

**Review by delaneymiranda1 — APPROVED** [review]
Great job adding those arguments. Nice helper methods. I might benefit from some of those helper methods when refactoring.

**Review by scottdevoss — APPROVED** [review]
These changes look good! Thank you!

**Pull request merged**
